# [package]
# name = "cross-contract-calls"
# version = "0.0.0"
# authors = ["Near Inc <hello@nearprotocol.com>"]
# edition = "2018"

[workspace]
members = [
  "contracts/*",
  "sandbox-linkdrop",
  # "contracts/linkdrop-proxy-callback"
]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

