[package]
name = "linkdrop-proxy"
version = "0.1.0"
authors = ["Ryan Mehta <ryan.mehta@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0-pre.1"
near-contract-standards = "4.0.0-pre.2"
serde = "1.0.0"
